# Generated by Django 2.1.13 on 2019-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='Store Name')),
                ('store_logo', models.ImageField(default='', upload_to='logo/%Y/%m/%d', verbose_name='Store Logo')),
            ],
        ),
    ]
