# Generated by Django 2.2.7 on 2019-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_storedetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedetails',
            options={'verbose_name': 'Store Details', 'verbose_name_plural': 'Store Details'},
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='products/%Y/%m/%d', verbose_name='Product Picture'),
        ),
    ]
