# Generated by Django 2.2 on 2020-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20191105_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer name')),
                ('item_description', models.TextField(max_length=500, verbose_name='Item Description')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Fully paid', 'Fully paid'), ('Got balnce', 'Got balance'), ('Not paid', 'Not paid')], default='Not paid', max_length=200, verbose_name='Payment Status')),
                ('amount_paid', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
