# Generated by Django 2.2 on 2020-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_creditor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditor',
            options={'verbose_name': 'Creditor', 'verbose_name_plural': 'Creditors'},
        ),
        migrations.AlterField(
            model_name='creditor',
            name='amount',
            field=models.IntegerField(verbose_name='Total Price'),
        ),
    ]
