# Generated by Django 2.2 on 2020-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20200209_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantity'),
        ),
    ]
